name: Test
on: push
jobs:
  test-isolated:
    name: 1.51.0 Bugs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: v1.51.0
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: v1.51.0/.nvmrc
          cache-dependency-path: v1.51.0/package-lock.json
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Setup playwright
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
