name: Test
on: push
jobs:
  v1-51-0-negative-duration:
    name: v1.51.0 Bugs (Negative Duration)
    runs-on: ubuntu-latest
    timeout-minutes: 90
    defaults:
      run:
        working-directory: v1.51.0
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: v1.51.0/.nvmrc
          cache-dependency-path: v1.51.0/package-lock.json
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Setup playwright
        run: npx playwright install "$BROWSER" --with-deps
        env:
          BROWSER: ${{matrix.browser}}
      - name: Run tests
        run: npm run test:negative-duration:$BROWSER
        env:
          BROWSER: ${{matrix.browser}}
